bridges = []

[[instances]]
name = "into_pieces"
id = "__into_pieces"
dna_hash = "QmNqz2PVGGwW28QDTsFvcg3sqBNY3dyv5uwxqdNfo6hS3d"
uri = "file:dist/into-pieces.dna.json" 

[[UIs]]
name = "Into Pieces"
id = "into_pieces_ui"
uri = "dir:gui" 

[[UIs.instance_references]]
ui_handle = "test-instance"
instance_id = "__into_pieces"
