bridges = []

[[instances]]
name = "into_pieces"
id = "__into_pieces"
dna_hash = "QmSwxJb9zPDJtdVzzKRv3Uirw6oDq7o6Uha3bZgUGWYACJ"
uri = "file:dist/into-pieces.dna.json" 

[[UIs]]
name = "Into Pieces"
id = "into_pieces_ui"
uri = "dir:gui" 

[[UIs.instance_references]]
ui_handle = "test-instance"
instance_id = "__into_pieces"
