bridges = []
persistence_dir = ''

[[agents]]
id = 'hc-run-agent'
keystore_file = 'Alice'
name = 'Alice'
public_address = 'HcSciaDXrXkqxwv7gukMChvazIuscvcrk457t8n88cmo95en4sPCEdDKvj4ucja'
test_agent = true

[[dnas]]
file = 'dist/into-pieces.dna.json'
hash = 'QmcNwT511Y1rtzxQ6v5bfNiGSf6fFi6scXbCGuE9BAeTbC'
id = '__into_pieces'

[[instances]]
agent = 'hc-run-agent'
dna = '__into_pieces'
id = '__into_pieces'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = false
choose_free_port = false
id = 'into_pieces_ui'

[[interfaces.instances]]
alias = 'test-instance'
id = '__into_pieces'

[interfaces.driver]
port = 50000
type = 'websocket'

[[ui_bundles]]
id = 'into_pieces_ui'
root_dir = 'gui'

[[ui_interfaces]]
bind_address = '127.0.0.1'
bundle = 'into_pieces_ui'
dna_interface = 'into_pieces_ui'
id = 'into_pieces_ui'
port = 8888
reroute_to_root = false

[logger]
state_dump = true
type = 'debug'

[logger.rules]
rules = []

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
